apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.tartgetPort }}
  selector:
    app: {{ .Values.app }}
  type: {{ .Values.service.type }} 
