namespace:
  name: sandbox
app: techtrends 
service:
  port: 4111
  type: ClusterIP
  protocol: TCP
  targetPort: 3111

image:
  repository: techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resourcesRequests:
  cpu: 250m
  memory: 64Mi
resourcesLimits:
  cpu: 500m
  memory: 128Mi  

containerPort: 3111
livenessProbe:
  httpGet:
    path: /healthz
    port: 3111
readinessProbe:
  httpGet:
    path: /healthz
    port: 3111    
